linters:
  enable-all: true
  disable:
    - nlreturn
    - exhaustivestruct
    - godox

linters-settings:
  cyclop:
    max-complexity: 15 # minimal code complexity to report, go-report-card uses 15.