linters:
  enable-all: true
  disable:
    - nlreturn
    - exhaustivestruct
    - godox

linters-settings:
  gocyclo:
    min-complexity: 11 # minimal code complexity to report, go-report-card uses 15.